CREATE TABLE USERS (
  USERNAME VARCHAR(255),
  PASSWORD VARCHAR(255),
  ROLE VARCHAR(255),
  PRIMARY KEY (USERNAME)
);

INSERT INTO USERS (USERNAME, PASSWORD, ROLE) VALUES
  ('admin', '$2a$10$.jv/pvDfehL4FzA1uS7hp.3S4/PPzu7.KCErsnB5j0kf2HvO2EowW', 'ROLE_USER');